# Cuál es el problema?

Abandono de clientes (Churn)

Trabajamos con una empresa de telecomunicaciones que quiere ***predecir cuales clientes van a abandonar el servicio*** (churn) para poder tomar acciones preventivas.

Por qué es importante?

* Conseguir un cliente nuevo representa entre 5x y 25x más que retener uno existente.
* Si podemos predecir quien se va, podemos ofrecerle un descuento o llamarlo antes de que cancele.

In [7]:
import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split # Dividir datos en entrenamiento y prueba
from sklearn.compose import ColumnTransformer # Para transformar columnas específicas
from sklearn.preprocessing import OneHotEncoder # Para escalar y codificar variables
from sklearn.linear_model import LogisticRegression # Modelo de regresión logística

# Metricas de evaluación para la clasificación

from sklearn.metrics import (
    confusion_matrix, # Matriz de confusión
    classification_report, # reporte con precisión, recall y f1-score
    accuracy_score, # Porcentaje de predicciones correctas
)

import matplotlib.pyplot as plt
print("Librerias cargadas correctamente")

Librerias cargadas correctamente

In [6]:
%pip install pandas numpy scikit-learn matplotlib

Collecting pandas
  Downloading pandas-3.0.1-cp313-cp313-win_amd64.whl.metadata (19 kB)
Collecting numpy
  Downloading numpy-2.4.2-cp313-cp313-win_amd64.whl.metadata (6.6 kB)
Collecting scikit-learn
  Downloading scikit_learn-1.8.0-cp313-cp313-win_amd64.whl.metadata (11 kB)
Collecting matplotlib
  Downloading matplotlib-3.10.8-cp313-cp313-win_amd64.whl.metadata (52 kB)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\ftrejos\appdata\roaming\python\python313\site-packages (from pandas) (2.9.0.post0)
Collecting tzdata (from pandas)
  Using cached tzdata-2025.3-py2.py3-none-any.whl.metadata (1.4 kB)
Collecting scipy>=1.10.0 (from scikit-learn)
  Downloading scipy-1.17.1-cp313-cp313-win_amd64.whl.metadata (60 kB)
Collecting joblib>=1.3.0 (from scikit-learn)
  Using cached joblib-1.5.3-py3-none-any.whl.metadata (5.5 kB)
Collecting threadpoolctl>=3.2.0 (from scikit-learn)
  Using cached threadpoolctl-3.6.0-py3-none-any.whl.metadata (13 kB)
Collecting contourpy>=1.0.1 (from matplotlib)
  Downloading contourpy-1.3.3-cp313-cp313-win_amd64.whl.metadata (5.5 kB)
Collecting cycler>=0.10 (from matplotlib)
  Using cached cycler-0.12.1-py3-none-any.whl.metadata (3.8 kB)
Collecting fonttools>=4.22.0 (from matplotlib)
  Downloading fonttools-4.61.1-cp313-cp313-win_amd64.whl.metadata (116 kB)
Collecting kiwisolver>=1.3.1 (from matplotlib)
  Downloading kiwisolver-1.4.9-cp313-cp313-win_amd64.whl.metadata (6.4 kB)
Requirement already satisfied: packaging>=20.0 in c:\users\ftrejos\appdata\roaming\python\python313\site-packages (from matplotlib) (26.0)
Collecting pillow>=8 (from matplotlib)
  Downloading pillow-12.1.1-cp313-cp313-win_amd64.whl.metadata (9.0 kB)
Collecting pyparsing>=3 (from matplotlib)
  Using cached pyparsing-3.3.2-py3-none-any.whl.metadata (5.8 kB)
Requirement already satisfied: six>=1.5 in c:\users\ftrejos\appdata\roaming\python\python313\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Downloading pandas-3.0.1-cp313-cp313-win_amd64.whl (9.7 MB)
   ---------------------------------------- 0.0/9.7 MB ? eta -:--:--
   --- ------------------------------------ 0.8/9.7 MB 4.7 MB/s eta 0:00:02
   ---------- ----------------------------- 2.6/9.7 MB 8.5 MB/s eta 0:00:01
   ------------------ --------------------- 4.5/9.7 MB 7.8 MB/s eta 0:00:01
   ----------------------------- ---------- 7.1/9.7 MB 9.0 MB/s eta 0:00:01
   -------------------------------------- - 9.4/9.7 MB 9.6 MB/s eta 0:00:01
   ---------------------------------------- 9.7/9.7 MB 9.3 MB/s  0:00:01
Downloading numpy-2.4.2-cp313-cp313-win_amd64.whl (12.3 MB)
   ---------------------------------------- 0.0/12.3 MB ? eta -:--:--
   ----- ---------------------------------- 1.8/12.3 MB 10.4 MB/s eta 0:00:02
   ------------ --------------------------- 3.9/12.3 MB 10.2 MB/s eta 0:00:01
   ------------------ --------------------- 5.8/12.3 MB 9.8 MB/s eta 0:00:01
   ----------------------- ---------------- 7.3/12.3 MB 9.2 MB/s eta 0:00:01
   ------------------------------ --------- 9.4/12.3 MB 9.3 MB/s eta 0:00:01
   ---------------------------------------  12.1/12.3 MB 9.9 MB/s eta 0:00:01
   ---------------------------------------- 12.3/12.3 MB 9.5 MB/s  0:00:01
Downloading scikit_learn-1.8.0-cp313-cp313-win_amd64.whl (8.0 MB)
   ---------------------------------------- 0.0/8.0 MB ? eta -:--:--
   ------ --------------------------------- 1.3/8.0 MB 7.5 MB/s eta 0:00:01
   ------------------ --------------------- 3.7/8.0 MB 9.8 MB/s eta 0:00:01
   ------------------------------- -------- 6.3/8.0 MB 9.8 MB/s eta 0:00:01
   ---------------------------------------- 8.0/8.0 MB 9.8 MB/s  0:00:00
Downloading matplotlib-3.10.8-cp313-cp313-win_amd64.whl (8.1 MB)
   ---------------------------------------- 0.0/8.1 MB ? eta -:--:--
   --------- ------------------------------ 1.8/8.1 MB 9.5 MB/s eta 0:00:01
   -------------------- ------------------- 4.2/8.1 MB 10.3 MB/s eta 0:00:01
   ----------------------------- ---------- 6.0/8.1 MB 9.9 MB/s eta 0:00:01
   ------------------------------------- -- 7.6/8.1 MB 9.1 MB/s eta 0:00:01
   ---------------------------------------- 8.1/8.1 MB 8.8 MB/s  0:00:00
Downloading contourpy-1.3.3-cp313-cp313-win_amd64.whl (226 kB)
Using cached cycler-0.12.1-py3-none-any.whl (8.3 kB)
Downloading fonttools-4.61.1-cp313-cp313-win_amd64.whl (2.3 MB)
   ---------------------------------------- 0.0/2.3 MB ? eta -:--:--
   ------------------ --------------------- 1.0/2.3 MB 7.0 MB/s eta 0:00:01
   ---------------------------------------- 2.3/2.3 MB 6.1 MB/s  0:00:00
Using cached joblib-1.5.3-py3-none-any.whl (309 kB)
Downloading kiwisolver-1.4.9-cp313-cp313-win_amd64.whl (73 kB)
Downloading pillow-12.1.1-cp313-cp313-win_amd64.whl (7.0 MB)
   ---------------------------------------- 0.0/7.0 MB ? eta -:--:--
   -------- ------------------------------- 1.6/7.0 MB 11.6 MB/s eta 0:00:01
   ------------------- -------------------- 3.4/7.0 MB 9.1 MB/s eta 0:00:01
   ------------------------------- -------- 5.5/7.0 MB 9.7 MB/s eta 0:00:01
   ---------------------------------------- 7.0/7.0 MB 9.3 MB/s  0:00:00
Using cached pyparsing-3.3.2-py3-none-any.whl (122 kB)
Downloading scipy-1.17.1-cp313-cp313-win_amd64.whl (36.5 MB)
   ---------------------------------------- 0.0/36.5 MB ? eta -:--:--
    --------------------------------------- 0.8/36.5 MB 3.9 MB/s eta 0:00:10
   -- ------------------------------------- 2.4/36.5 MB 6.2 MB/s eta 0:00:06
   ---- ----------------------------------- 3.9/36.5 MB 6.2 MB/s eta 0:00:06
   ----- ---------------------------------- 5.0/36.5 MB 6.2 MB/s eta 0:00:06
   ------ --------------------------------- 6.0/36.5 MB 5.8 MB/s eta 0:00:06
   ------ --------------------------------- 6.3/36.5 MB 5.3 MB/s eta 0:00:06
   ------- -------------------------------- 6.8/36.5 MB 4.6 MB/s eta 0:00:07
   ------- -------------------------------- 6.8/36.5 MB 4.6 MB/s eta 0:00:07
   ------- -------------------------------- 7.1/36.5 MB 3.9 MB/s eta 0:00:08
   ------- -------------------------------- 7.1/36.5 MB 3.9 MB/s eta 0:00:08
   -------- ------------------------------- 7.3/36.5 MB 3.1 MB/s eta 0:00:10
   -------- ------------------------------- 7.3/36.5 MB 3.1 MB/s eta 0:00:10
   -------- ------------------------------- 7.3/36.5 MB 3.1 MB/s eta 0:00:10
   -------- ------------------------------- 7.3/36.5 MB 3.1 MB/s eta 0:00:10
   -------- ------------------------------- 7.6/36.5 MB 2.3 MB/s eta 0:00:13
   -------- ------------------------------- 7.6/36.5 MB 2.3 MB/s eta 0:00:13
   -------- ------------------------------- 7.6/36.5 MB 2.3 MB/s eta 0:00:13
   -------- ------------------------------- 7.6/36.5 MB 2.3 MB/s eta 0:00:13
   -------- ------------------------------- 7.9/36.5 MB 2.0 MB/s eta 0:00:15
   -------- ------------------------------- 7.9/36.5 MB 2.0 MB/s eta 0:00:15
   -------- ------------------------------- 8.1/36.5 MB 1.8 MB/s eta 0:00:16
   -------- ------------------------------- 8.1/36.5 MB 1.8 MB/s eta 0:00:16
   --------- ------------------------------ 8.4/36.5 MB 1.7 MB/s eta 0:00:17
   --------- ------------------------------ 8.7/36.5 MB 1.7 MB/s eta 0:00:17
   --------- ------------------------------ 8.7/36.5 MB 1.7 MB/s eta 0:00:17
   --------- ------------------------------ 8.9/36.5 MB 1.6 MB/s eta 0:00:17
   ---------- ----------------------------- 9.2/36.5 MB 1.6 MB/s eta 0:00:17
   ---------- ----------------------------- 9.4/36.5 MB 1.6 MB/s eta 0:00:17
   ---------- ----------------------------- 9.7/36.5 MB 1.6 MB/s eta 0:00:17
   ----------- ---------------------------- 10.2/36.5 MB 1.6 MB/s eta 0:00:17
   ----------- ---------------------------- 10.5/36.5 MB 1.6 MB/s eta 0:00:17
   ------------ --------------------------- 11.0/36.5 MB 1.6 MB/s eta 0:00:16
   ------------ --------------------------- 11.5/36.5 MB 1.6 MB/s eta 0:00:16
   ------------- -------------------------- 12.1/36.5 MB 1.7 MB/s eta 0:00:15
   -------------- ------------------------- 12.8/36.5 MB 1.7 MB/s eta 0:00:14
   -------------- ------------------------- 13.4/36.5 MB 1.7 MB/s eta 0:00:14
   --------------- ------------------------ 13.9/36.5 MB 1.8 MB/s eta 0:00:13
   ---------------- ----------------------- 14.7/36.5 MB 1.8 MB/s eta 0:00:13
   ---------------- ----------------------- 15.5/36.5 MB 1.9 MB/s eta 0:00:12
   ----------------- ---------------------- 16.3/36.5 MB 1.9 MB/s eta 0:00:11
   ------------------ --------------------- 17.0/36.5 MB 2.0 MB/s eta 0:00:10
   ------------------- -------------------- 18.1/36.5 MB 2.0 MB/s eta 0:00:10
   -------------------- ------------------- 18.9/36.5 MB 2.1 MB/s eta 0:00:09
   --------------------- ------------------ 19.4/36.5 MB 2.1 MB/s eta 0:00:09
   ---------------------- ----------------- 20.2/36.5 MB 2.1 MB/s eta 0:00:08
   ---------------------- ----------------- 20.7/36.5 MB 2.1 MB/s eta 0:00:08
   ----------------------- ---------------- 21.2/36.5 MB 2.1 MB/s eta 0:00:08
   ------------------------ --------------- 22.0/36.5 MB 2.2 MB/s eta 0:00:07
   ------------------------ --------------- 22.8/36.5 MB 2.2 MB/s eta 0:00:07
   ------------------------- -------------- 23.6/36.5 MB 2.2 MB/s eta 0:00:06
   -------------------------- ------------- 24.6/36.5 MB 2.3 MB/s eta 0:00:06
   --------------------------- ------------ 25.4/36.5 MB 2.3 MB/s eta 0:00:05
   ---------------------------- ----------- 26.0/36.5 MB 2.3 MB/s eta 0:00:05
   ----------------------------- ---------- 26.7/36.5 MB 2.3 MB/s eta 0:00:05
   ------------------------------ --------- 27.5/36.5 MB 2.4 MB/s eta 0:00:04
   ------------------------------- -------- 28.3/36.5 MB 2.4 MB/s eta 0:00:04
   ------------------------------- -------- 28.8/36.5 MB 2.4 MB/s eta 0:00:04
   -------------------------------- ------- 29.6/36.5 MB 2.4 MB/s eta 0:00:03
   --------------------------------- ------ 30.1/36.5 MB 2.4 MB/s eta 0:00:03
   --------------------------------- ------ 30.9/36.5 MB 2.4 MB/s eta 0:00:03
   ---------------------------------- ----- 31.7/36.5 MB 2.5 MB/s eta 0:00:02
   ----------------------------------- ---- 32.8/36.5 MB 2.5 MB/s eta 0:00:02
   ------------------------------------- -- 33.8/36.5 MB 2.5 MB/s eta 0:00:02
   ------------------------------------- -- 34.1/36.5 MB 2.5 MB/s eta 0:00:01
   ------------------------------------- -- 34.6/36.5 MB 2.5 MB/s eta 0:00:01
   -------------------------------------- - 35.1/36.5 MB 2.5 MB/s eta 0:00:01
   ---------------------------------------  35.7/36.5 MB 2.5 MB/s eta 0:00:01
   ---------------------------------------  36.4/36.5 MB 2.5 MB/s eta 0:00:01
   ---------------------------------------- 36.5/36.5 MB 2.5 MB/s  0:00:14
Using cached threadpoolctl-3.6.0-py3-none-any.whl (18 kB)
Using cached tzdata-2025.3-py2.py3-none-any.whl (348 kB)
Installing collected packages: tzdata, threadpoolctl, pyparsing, pillow, numpy, kiwisolver, joblib, fonttools, cycler, scipy, pandas, contourpy, scikit-learn, matplotlib

   ----------------------------------------  0/14 [tzdata]
   ----------------------------------------  0/14 [tzdata]
   -- -------------------------------------  1/14 [threadpoolctl]
   ----- ----------------------------------  2/14 [pyparsing]
   -------- -------------------------------  3/14 [pillow]
   -------- -------------------------------  3/14 [pillow]
   -------- -------------------------------  3/14 [pillow]
   -------- -------------------------------  3/14 [pillow]
   -------- -------------------------------  3/14 [pillow]
   ----------- ----------------------------  4/14 [numpy]
   ----------- ----------------------------  4/14 [numpy]
   ----------- ----------------------------  4/14 [numpy]
   ----------- ----------------------------  4/14 [numpy]
   ----------- ----------------------------  4/14 [numpy]
   ----------- ----------------------------  4/14 [numpy]
   ----------- ----------------------------  4/14 [numpy]
   ----------- ----------------------------  4/14 [numpy]
   ----------- ----------------------------  4/14 [numpy]
   ----------- ----------------------------  4/14 [numpy]
   ----------- ----------------------------  4/14 [numpy]
   ----------- ----------------------------  4/14 [numpy]
   ----------- ----------------------------  4/14 [numpy]
   ----------- ----------------------------  4/14 [numpy]
   ----------- ----------------------------  4/14 [numpy]
   ----------- ----------------------------  4/14 [numpy]
   ----------- ----------------------------  4/14 [numpy]
   ----------- ----------------------------  4/14 [numpy]
   ----------- ----------------------------  4/14 [numpy]
   ----------- ----------------------------  4/14 [numpy]
   ----------- ----------------------------  4/14 [numpy]
   ----------- ----------------------------  4/14 [numpy]
   ----------- ----------------------------  4/14 [numpy]
   ----------- ----------------------------  4/14 [numpy]
   ----------- ----------------------------  4/14 [numpy]
   ----------- ----------------------------  4/14 [numpy]
   ----------- ----------------------------  4/14 [numpy]
   ----------- ----------------------------  4/14 [numpy]
   ----------- ----------------------------  4/14 [numpy]
   ----------------- ----------------------  6/14 [joblib]
   ----------------- ----------------------  6/14 [joblib]
   ----------------- ----------------------  6/14 [joblib]
   -------------------- -------------------  7/14 [fonttools]
   -------------------- -------------------  7/14 [fonttools]
   -------------------- -------------------  7/14 [fonttools]
   -------------------- -------------------  7/14 [fonttools]
   -------------------- -------------------  7/14 [fonttools]
   -------------------- -------------------  7/14 [fonttools]
   -------------------- -------------------  7/14 [fonttools]
   -------------------- -------------------  7/14 [fonttools]
   -------------------- -------------------  7/14 [fonttools]
   -------------------- -------------------  7/14 [fonttools]
   -------------------- -------------------  7/14 [fonttools]
   -------------------- -------------------  7/14 [fonttools]
   -------------------- -------------------  7/14 [fonttools]
   -------------------- -------------------  7/14 [fonttools]
   -------------------- -------------------  7/14 [fonttools]
   -------------------- -------------------  7/14 [fonttools]
   -------------------- -------------------  7/14 [fonttools]
   ------------------------- --------------  9/14 [scipy]
   ------------------------- --------------  9/14 [scipy]
   ------------------------- --------------  9/14 [scipy]
   ------------------------- --------------  9/14 [scipy]
   ------------------------- --------------  9/14 [scipy]
   ------------------------- --------------  9/14 [scipy]
   ------------------------- --------------  9/14 [scipy]
   ------------------------- --------------  9/14 [scipy]
   ------------------------- --------------  9/14 [scipy]
   ------------------------- --------------  9/14 [scipy]
   ------------------------- --------------  9/14 [scipy]
   ------------------------- --------------  9/14 [scipy]
   ------------------------- --------------  9/14 [scipy]
   ------------------------- --------------  9/14 [scipy]
   ------------------------- --------------  9/14 [scipy]
   ------------------------- --------------  9/14 [scipy]
   ------------------------- --------------  9/14 [scipy]
   ------------------------- --------------  9/14 [scipy]
   ------------------------- --------------  9/14 [scipy]
   ------------------------- --------------  9/14 [scipy]
   ------------------------- --------------  9/14 [scipy]
   ------------------------- --------------  9/14 [scipy]
   ------------------------- --------------  9/14 [scipy]
   ------------------------- --------------  9/14 [scipy]
   ------------------------- --------------  9/14 [scipy]
   ------------------------- --------------  9/14 [scipy]
   ------------------------- --------------  9/14 [scipy]
   ------------------------- --------------  9/14 [scipy]
   ------------------------- --------------  9/14 [scipy]
   ------------------------- --------------  9/14 [scipy]
   ------------------------- --------------  9/14 [scipy]
   ------------------------- --------------  9/14 [scipy]
   ------------------------- --------------  9/14 [scipy]
   ------------------------- --------------  9/14 [scipy]
   ------------------------- --------------  9/14 [scipy]
   ------------------------- --------------  9/14 [scipy]
   ------------------------- --------------  9/14 [scipy]
   ------------------------- --------------  9/14 [scipy]
   ------------------------- --------------  9/14 [scipy]
   ------------------------- --------------  9/14 [scipy]
   ------------------------- --------------  9/14 [scipy]
   ------------------------- --------------  9/14 [scipy]
   ------------------------- --------------  9/14 [scipy]
   ------------------------- --------------  9/14 [scipy]
   ------------------------- --------------  9/14 [scipy]
   ------------------------- --------------  9/14 [scipy]
   ------------------------- --------------  9/14 [scipy]
   ------------------------- --------------  9/14 [scipy]
   ------------------------- --------------  9/14 [scipy]
   ------------------------- --------------  9/14 [scipy]
   ------------------------- --------------  9/14 [scipy]
   ------------------------- --------------  9/14 [scipy]
   ------------------------- --------------  9/14 [scipy]
   ------------------------- --------------  9/14 [scipy]
   ------------------------- --------------  9/14 [scipy]
   ------------------------- --------------  9/14 [scipy]
   ------------------------- --------------  9/14 [scipy]
   ------------------------- --------------  9/14 [scipy]
   ------------------------- --------------  9/14 [scipy]
   ------------------------- --------------  9/14 [scipy]
   ------------------------- --------------  9/14 [scipy]
   ------------------------- --------------  9/14 [scipy]
   ---------------------------- ----------- 10/14 [pandas]
   ---------------------------- ----------- 10/14 [pandas]
   ---------------------------- ----------- 10/14 [pandas]
   ---------------------------- ----------- 10/14 [pandas]
   ---------------------------- ----------- 10/14 [pandas]
   ---------------------------- ----------- 10/14 [pandas]
   ---------------------------- ----------- 10/14 [pandas]
   ---------------------------- ----------- 10/14 [pandas]
   ---------------------------- ----------- 10/14 [pandas]
   ---------------------------- ----------- 10/14 [pandas]
   ---------------------------- ----------- 10/14 [pandas]
   ---------------------------- ----------- 10/14 [pandas]
   ---------------------------- ----------- 10/14 [pandas]
   ---------------------------- ----------- 10/14 [pandas]
   ---------------------------- ----------- 10/14 [pandas]
   ---------------------------- ----------- 10/14 [pandas]
   ---------------------------- ----------- 10/14 [pandas]
   ---------------------------- ----------- 10/14 [pandas]
   ---------------------------- ----------- 10/14 [pandas]
   ---------------------------- ----------- 10/14 [pandas]
   ---------------------------- ----------- 10/14 [pandas]
   ---------------------------- ----------- 10/14 [pandas]
   ---------------------------- ----------- 10/14 [pandas]
   ---------------------------- ----------- 10/14 [pandas]
   ---------------------------- ----------- 10/14 [pandas]
   ---------------------------- ----------- 10/14 [pandas]
   ---------------------------- ----------- 10/14 [pandas]
   ---------------------------- ----------- 10/14 [pandas]
   ---------------------------- ----------- 10/14 [pandas]
   ---------------------------- ----------- 10/14 [pandas]
   ---------------------------- ----------- 10/14 [pandas]
   ---------------------------- ----------- 10/14 [pandas]
   ---------------------------- ----------- 10/14 [pandas]
   ---------------------------- ----------- 10/14 [pandas]

  WARNING: The scripts f2py.exe and numpy-config.exe are installed in 'c:\Users\Ftrejos\AppData\Local\Programs\Python\Python313\Scripts' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
  WARNING: The scripts fonttools.exe, pyftmerge.exe, pyftsubset.exe and ttx.exe are installed in 'c:\Users\Ftrejos\AppData\Local\Programs\Python\Python313\Scripts' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.

[notice] A new release of pip is available: 25.2 -> 26.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [9]:
#Cargar el archivo CSV en un DataFrame (tabla de datos  )
df = pd.read_csv("abandono_clientes.csv")
# Mostrar las primeras filas del DataFrame para verificar que se cargó correctamente
print("primeras 5 filas del DataSet:")
df.head()

primeras 5 filas del DataSet:

,antiguedad_meses,factura_mensual,llamadas_soporte,contrato,satisfaccion,abandono
0,52,61.18,0,Dos_anios,3,0
1,15,54.89,1,Mensual,1,1
2,72,112.95,3,Anual,2,0
3,61,103.06,0,Mensual,1,1
4,21,116.50,2,Mensual,1,1

In [10]:
# Informacion general del dataset
print(f"Filas: {df.shape[0]}, Columnas: {df.shape[1]}")
print()

# Tipo de dato de cada columna
print("Tipos de datos:")
for col, dtype in df.dtypes.items():
    print(f"  {col:20s} -> {dtype}")

print()

# Verificar valores faltantes
nulos = df.isna().sum()
if nulos.sum() == 0:
    print("No hay valores faltantes en el dataset.")
else:
    print(f"ATENCION: hay {nulos.sum()} valores nulos.")
    print(nulos[nulos > 0])

Filas: 800, Columnas: 6

Tipos de datos:
  antiguedad_meses     -> int64
  factura_mensual      -> float64
  llamadas_soporte     -> int64
  contrato             -> str
  satisfaccion         -> int64
  abandono             -> int64

No hay valores faltantes en el dataset.

In [11]:
conteo = df["abandono"].value_counts()
porcentaje = df["abandono"].value_counts(normalize=True) * 100

print("Distribucion de la variable objetivo (abandono):")
print(f"  Permanece (0): {conteo[0]} clientes ({porcentaje[0]:.1f}%)")
print(f"  Abandona  (1): {conteo[1]} clientes ({porcentaje[1]:.1f}%)")
print()
print("Las clases estan moderadamente desbalanceadas.")
print("Hay mas clientes que permanecen que clientes que abandonan.")
print("Esto es lo tipico en la realidad: la mayoria de clientes NO se van.")

Distribucion de la variable objetivo (abandono):
  Permanece (0): 517 clientes (64.6%)
  Abandona  (1): 283 clientes (35.4%)

Las clases estan moderadamente desbalanceadas.
Hay mas clientes que permanecen que clientes que abandonan.
Esto es lo tipico en la realidad: la mayoria de clientes NO se van.

# Analisis exporatorio: Como se comportan las variables segun abandono?

## Antes de entrana el modelo, vemos si las variables tiene relación con el abandono. Esto nos ayuda a entender que factores podrian influir en la decisión del cliente

In [14]:
#Comporar el promedio de cada variable 

comparacion = df.groupby("abandono")[["antiguedad_meses","factura_mensual",
                                      "llamadas_soporte","satisfaccion"]].mean().round(2)
comparacion.index=["Permanece (0)","Abandona (1)"]
print("Promedio de variables numerica segun abandono:")
comparacion

Promedio de variables numerica segun abandono:

,antiguedad_meses,factura_mensual,llamadas_soporte,satisfaccion
Permanece (0),39.43,67.02,1.88,3.14
Abandona (1),28.41,77.27,2.28,2.67

In [16]:
# Analisi del tipo contrato vs el abandono
tabla_contrato = pd.crosstab(
    df["contrato"], 
    df["abandono"], 
    normalize="index"
    ) * 100
tabla_contrato.columns = ["Permanece (%)", "Abandona (%)"]
print("porcentaje de abandono pro tipo de contrato:")
comparacion

porcentaje de abandono pro tipo de contrato:

,antiguedad_meses,factura_mensual,llamadas_soporte,satisfaccion
Permanece (0),39.43,67.02,1.88,3.14
Abandona (1),28.41,77.27,2.28,2.67

# Preapara los datos para el modelo.

1. Separar variables predictoras (x) de la variable objetivo (y)
2. Entrenar los datoas con el (80%) del dataset y prueba con el (20%) del dataset

In [19]:
# Paso 1 separar X(vriables predictoas) e y (variabl objetivo)
X= df[["antiguedad_meses","factura_mensual","llamadas_soporte",
        "satisfaccion","contrato"]]
y=df["abandono"]

# Paso 2 Dividir el conjunto de entrenamiento (80%) y prueba (20%)
X_train, X_test, y_train, y_test = train_test_split(
    X, y,
     test_size=0.2, # 20% para prueba
     random_state=42, # 80% para reproducibilidad
        stratify=y
)

print(f"Datos de entrenamiento: {X_train.shape[0]} Clientes")
print(f"Datos de prueba: {X_test.shape[0]} Clientes")
print("\n")
print(f"Proporcion de abandono en entrenamiento: {y_train.mean()*100:.1f}%")
print(f"Proporcion de abandono en prueba: {y_test.mean()*100:.1f}%")
print()
print("La proporciones son similares gracias al parametro 'stratify=y' en train_test_split")

Datos de entrenamiento: 640 Clientes
Datos de prueba: 160 Clientes


Proporcion de abandono en entrenamiento: 35.3%
Proporcion de abandono en prueba: 35.6%

La proporciones son similares gracias al parametro 'stratify=y' en train_test_split

# Construir  el pipeline y entrenar el modelo

1. Calula una puntuación lineal
2.Pasa por una puntación que la convierte en probabilidad entre 0 y 1
3. SI la probabilidad es mayor a 0.5  predice la clase 1 (abandona): si no, predice 0 (permanece)

In [23]:
from sklearn.pipeline import Pipeline

numeric_features = ["antiguedad_meses", "factura_mensual",
                    "llamadas_soporte", "satisfaccion"]
categorical_features = ["contrato"]


preprocess = ColumnTransformer(
    transformers=[
        ("num", "passthrough", numeric_features),
        ("cat", OneHotEncoder(handle_unknown="ignore"), categorical_features),
    ]
)


pipe = Pipeline(steps=[
    ("preprocess", preprocess),
    ("model", LogisticRegression(max_iter=1000)),
])

# Entrenar el modelo con los datos de entrenamiento
pipe.fit(X_train, y_train)

print("Modelo entranado correctamente.")

Modelo entranado correctamente.

# Hacer predicciones
Usamos el modulo entranado para predecir el abandono en los datos de pruebas

In [25]:
# Generar prediciones con los datos de prueba
y_pred = pipe.predict(X_test)

# Mostrar las primeras 10 predicciones
comparacion_pred = pd.DataFrame({
    "Real": y_test.values[:10],
    "Prediccion": y_pred[:10],
    "Correcto": ["Si" if r == p else "No" for r, p in zip(y_test.values[:10], y_pred[:10])]
})

print("Primeras 10 predicciones vs realidad:")
print()
comparacion_pred

Primeras 10 predicciones vs realidad:

   Real  Prediccion Correcto
0     1           1       Si
1     0           0       Si
2     0           0       Si
3     0           0       Si
4     0           0       Si
5     0           0       Si
6     0           0       Si
7     0           0       Si
8     0           0       Si
9     0           0       Si

# Evaluación del modulo:  exactitud/presución (Acurracy)

Cuando hablamos del porcentaje de presición nos referimos a las predicciones que fueron correctas

Accurracy= predicciones Correctas /Total de predicciones.

Ejemplo: Si el 95% de clientes **NO** abandona, un modelo que siempre diga "No abandona" tendria un 95% de presicion, pero jamas detectaria a un cliente en riegos. seria inutil.

In [26]:
acc=accuracy_score(y_test, y_pred)
print(f"Accuracy (exactitud): {acc:.4f} ({acc*100:.2f}%%)")
print()
print(f"Esto significa que el modulo acerto {acc*100:.2f}% predicciones.")

Accuracy (exactitud): 0.7625 (76.25%%)

Esto significa que el modulo acerto 76.25% predicciones.